org: brettm12345
app: beat-the-books-api
service: beat-the-books-api

package:
  include:
    - src/**
plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: graphql
          method: post
          cors: true
