version: 2
jobs:
  test-and-lint:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'test-results/jest/results.xml'
      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Deploy
          command: yarn deploy
workflows:
  version: 2
  beat-the-books:
    jobs:
      - test-and-lint:
          context: test
      - deploy:
          requires:
            - test-and-lint
          context: deploy
