# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test-and-lint:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - run:
          name: Deploy
          command: yarn deploy
workflows:
  version: 2
  beat-the-books:
    jobs:
      - install-dependencies
      - test-and-lint:
          context: test
          requires:
            - install-dependencies
      - deploy:
          requires:
            - test-and-lint
          context: deploy
